"use client";
import { useEffect,useState } from "react";
import { ArrowLeft,Grid3X3,Heart,MessageCircle,Send,UserCheck,UserPlus,Play } from "lucide-react";
import { useParams,useRouter } from "next/navigation";
import { supabase } from "../../../lib/supabase";
type Profile={id:string;username:string;display_name:string;avatar_url:string|null;bio:string|null};
type Video={id:string;video_url:string;caption:string;likes_count:number;comments_count:number};
export default function UserProfilePage(){
 const params=useParams<{id:string}>(),router=useRouter(),id=params.id;const[profile,setProfile]=useState<Profile|null>(null),[videos,setVideos]=useState<Video[]>([]),[followers,setFollowers]=useState(0),[following,setFollowing]=useState(0),[likes,setLikes]=useState(0),[isFollowing,setIsFollowing]=useState(false),[me,setMe]=useState<string|null>(null),[loading,setLoading]=useState(true),[working,setWorking]=useState(false);
 useEffect(()=>{(async()=>{if(!supabase)return;const{data:{session}}=await supabase.auth.getSession(),uid=session?.user.id||null;setMe(uid);const[{data:p},{data:works},{count:fc},{count:fg}]=await Promise.all([supabase.from("profiles").select("id,username,display_name,avatar_url,bio").eq("id",id).maybeSingle(),supabase.from("videos").select("id,video_url,caption,likes_count,comments_count").eq("user_id",id).order("created_at",{ascending:false}),supabase.from("follows").select("follower_id",{count:"exact",head:true}).eq("following_id",id),supabase.from("follows").select("following_id",{count:"exact",head:true}).eq("follower_id",id)]);if(!p){setLoading(false);return}setProfile(p);setVideos(works||[]);setFollowers(fc||0);setFollowing(fg||0);setLikes((works||[]).reduce((s:number,v:Video)=>s+(v.likes_count||0),0));if(uid){const{data:f}=await supabase.from("follows").select("following_id").eq("follower_id",uid).eq("following_id",id).maybeSingle();setIsFollowing(!!f)}setLoading(false)})();},[id]);
 async function follow(){if(!supabase||!me){router.push("/auth");return}if(me===id)return;setWorking(true);if(isFollowing){await supabase.from("follows").delete().eq("follower_id",me).eq("following_id",id);setIsFollowing(false);setFollowers(x=>Math.max(0,x-1))}else{const{error}=await supabase.from("follows").insert({follower_id:me,following_id:id});if(!error){setIsFollowing(true);setFollowers(x=>x+1)}}setWorking(false)}
 async function message(){if(!supabase||!me){router.push("/auth");return}const{data,error}=await supabase.rpc("ensure_conversation",{p_user_id:id});if(error){alert(error.message);return}router.push(`/messages/${data}`)}
 if(loading)return <main className="profile-loading">加载中…</main>;if(!profile)return <main className="profile-loading">用户不存在</main>;const initial=(profile.display_name||profile.username||"星").slice(0,1).toUpperCase();
 return <main className="profile-page"><header className="profile-header"><button className="back-button" onClick={()=>router.back()}><ArrowLeft size={21}/></button><strong>@{profile.username}</strong><span/></header><section className="profile-top"><div className="profile-avatar">{profile.avatar_url?<img src={profile.avatar_url} alt="头像"/>:initial}</div><h1>{profile.display_name||profile.username}</h1><p>@{profile.username}</p><p className="profile-bio">{profile.bio||"记录生活，分享美好。"}</p><div className="profile-actions"><button className={isFollowing?"profile-follow following":"profile-follow"} disabled={working||me===id} onClick={follow}>{isFollowing?<><UserCheck size={17}/>已关注</>:<><UserPlus size={17}/>关注</>}</button>{me!==id&&<button className="profile-message" onClick={message}><MessageCircle size={17}/>私信</button>}</div></section><section className="stats"><div><strong>{following}</strong><span>关注</span></div><div><strong>{followers}</strong><span>粉丝</span></div><div><strong>{fmt(likes)}</strong><span>获赞</span></div></section><section className="profile-tabs"><button className="active"><Grid3X3 size={18}/>作品 {videos.length}</button><button onClick={message}><Send size={17}/>发私信</button></section>{videos.length?<section className="works-grid">{videos.map(v=><button className="work-card" key={v.id} onClick={()=>router.push(`/?video=${v.id}`)}><video src={v.video_url} muted playsInline preload="metadata"/><span className="playBadge"><Play size={14} fill="white"/></span><span className="workStats"><Heart size={13} fill="white"/> {fmt(v.likes_count||0)}</span></button>)}</section>:<section className="empty-content"><div className="empty-icon"><Grid3X3 size={27}/></div><h2>还没有作品</h2><p>这个用户还没有发布视频</p></section>}<nav className="profile-bottom"><button onClick={()=>router.push("/")}><Grid3X3 size={20}/><span>首页</span></button><button className="plus" onClick={()=>router.push(me?"/upload":"/auth")}>＋</button><button onClick={()=>router.push("/messages")}><MessageCircle size={20}/><span>消息</span></button></nav></main>;
}
function fmt(n:number){return n>=10000?(n/10000).toFixed(1).replace(".0","")+"万":n.toLocaleString("zh-CN")}
