"use client";
import{useEffect,useState}from"react";import{ArrowLeft,Heart,MessageCircle,UserPlus,Bell,CheckCheck}from"lucide-react";import{supabase}from"../../lib/supabase";
type Notice={id:string;type:string;payload:any;created_at:string;read:boolean;actor:string;avatar:string};
export default function NotificationsPage(){const[items,setItems]=useState<Notice[]>([]);const[loading,setLoading]=useState(true);const[uid,setUid]=useState<string|null>(null);
const load=async(id:string)=>{if(!supabase)return;const{data}=await supabase.from("notifications").select("id,type,payload,read,created_at,actor_id").eq("user_id",id).order("created_at",{ascending:false}).limit(100);const rows=data||[];const ids=[...new Set(rows.map((x:any)=>x.actor_id).filter(Boolean))];const{data:ps}=ids.length?await supabase.from("profiles").select("id,username,nickname,avatar_url").in("id",ids):{data:[]as any[]};setItems(rows.map((n:any)=>{const p=ps?.find((x:any)=>x.id===n.actor_id);const name=p?.nickname||p?.username||"有人";return{id:n.id,type:n.type,payload:n.payload||{},created_at:n.created_at,read:!!n.read,actor:name,avatar:p?.avatar_url||name.slice(0,1)}}));setLoading(false)};
useEffect(()=>{let channel:any;(async()=>{if(!supabase){setLoading(false);return}const{data:{session}}=await supabase.auth.getSession();if(!session){location.href="/auth";return}setUid(session.user.id);await load(session.user.id);channel=supabase.channel(`notice-${session.user.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"notifications",filter:`user_id=eq.${session.user.id}`},()=>load(session.user.id)).subscribe()})();return()=>{if(channel)supabase.removeChannel(channel)}},[]);
async function markAll(){if(!supabase||!uid)return;await supabase.from("notifications").update({read:true}).eq("user_id",uid).eq("read",false);setItems(x=>x.map(n=>({...n,read:true})))}
async function markOne(id:string){if(!supabase||!uid)return;await supabase.from("notifications").update({read:true}).eq("id",id).eq("user_id",uid);setItems(x=>x.map(n=>n.id===id?{...n,read:true}:n))}
const unread=items.filter(n=>!n.read).length;return <main className="noticePage"><style jsx global>{`.noticePage{min-height:100dvh;background:#070707;color:#fff;padding-bottom:30px}.noticeHead{height:60px;display:flex;align-items:center;justify-content:space-between;padding:0 15px;border-bottom:1px solid #ffffff12;position:sticky;top:0;background:#070707ee;backdrop-filter:blur(16px);z-index:5}.noticeHead h1{font-size:18px;margin:0}.headBtn{width:38px;height:38px;display:grid;place-items:center;background:none;border:0;color:#fff}.markBtn{display:flex;align-items:center;gap:5px;background:none;border:0;color:#aaa;font-size:12px}.noticeSummary{padding:13px 16px;color:#888;font-size:12px}.noticeList{padding:0 10px}.noticeRow{width:100%;display:flex;align-items:flex-start;gap:12px;padding:15px 7px;border:0;border-bottom:1px solid #ffffff09;background:transparent;color:#fff;text-align:left}.noticeRow.unread{background:#111}.socialAvatar{width:50px;height:50px;flex:0 0 50px;border-radius:50%;background:linear-gradient(135deg,#fff,#777);color:#111;display:grid;place-items:center;font-weight:900;font-size:19px;overflow:hidden}.socialAvatar img{width:100%;height:100%;object-fit:cover}.noticeBody{flex:1;line-height:1.5}.noticeBody b{margin-right:4px}.noticeBody small{display:block;color:#666;font-size:11px;margin-top:5px}.noticeBody p{margin:7px 0 0;color:#aaa;background:#121212;border-radius:8px;padding:8px 10px;font-size:13px}.noticeIcon{color:#aaa;margin-top:6px}.dot{width:7px;height:7px;border-radius:50%;background:#ff304f;margin-top:7px}.emptyState{min-height:70vh;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;color:#777}.emptyState b{color:#ddd}`}</style><header className="noticeHead"><button className="headBtn" onClick={()=>history.back()}><ArrowLeft/></button><h1>通知</h1><button className="markBtn" onClick={markAll}><CheckCheck size={16}/>全部已读</button></header><div className="noticeSummary">{unread?`${unread} 条未读通知`:`全部已读`}</div>{loading?<div className="emptyState">正在加载…</div>:items.length?<div className="noticeList">{items.map(n=><button className={`noticeRow ${n.read?"":"unread"}`} key={n.id} onClick={()=>markOne(n.id)}><div className="socialAvatar">{n.avatar.startsWith("http")?<img src={n.avatar} alt=""/>:n.avatar}</div><div className="noticeBody"><div><b>@{n.actor}</b>{textFor(n.type)}</div><small>{timeAgo(n.created_at)}</small>{n.payload?.content&&<p>{n.payload.content}</p>}</div><span className="noticeIcon">{n.type==="like"?<Heart size={20} fill="currentColor"/>:n.type==="comment"?<MessageCircle size={20}/>:n.type==="follow"?<UserPlus size={20}/>:<Bell size={20}/>}</span>{!n.read&&<span className="dot"/>}</button>)}</div>:<div className="emptyState"><Bell size={48}/><b>暂无通知</b><span>有人点赞、评论或关注你时会出现在这里</span></div>}</main>}
function textFor(t:string){return t==="like"?"赞了你的作品":t==="comment"?"评论了你的作品":t==="follow"?"关注了你":"给你发来一条通知"}function timeAgo(s:string){const m=Math.floor((Date.now()-new Date(s).getTime())/60000);if(m<1)return"刚刚";if(m<60)return`${m}分钟前`;const h=Math.floor(m/60);if(h<24)return`${h}小时前`;const d=Math.floor(h/24);return d<7?`${d}天前`:new Date(s).toLocaleDateString("zh-CN")}
