"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, UserPlus, UserCheck, Users } from "lucide-react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Person={id:string;username:string;nickname:string|null;display_name:string|null;avatar_url:string|null;bio:string|null};
export default function FollowersPage(){const router=useRouter();const [people,setPeople]=useState<Person[]>([]),[followingIds,setFollowingIds]=useState<Set<string>>(new Set()),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[toast,setToast]=useState("");
useEffect(()=>{(async()=>{if(!supabase){router.replace("/auth");return}const {data:{session}}=await supabase.auth.getSession();if(!session){router.replace("/auth");return}const {data:rows}=await supabase.from("follows").select("follower_id,created_at").eq("following_id",session.user.id).order("created_at",{ascending:false});const ids=(rows||[]).map((x:any)=>x.follower_id);if(!ids.length){setLoading(false);return}const [{data:p},{data:mine}]=await Promise.all([supabase.from("profiles").select("id,username,nickname,display_name,avatar_url,bio").in("id",ids),supabase.from("follows").select("following_id").eq("follower_id",session.user.id).in("following_id",ids)]);const map=new Map((p||[]).map((x:any)=>[x.id,x]));setPeople(ids.map(id=>map.get(id)).filter(Boolean));setFollowingIds(new Set((mine||[]).map((x:any)=>x.following_id)));setLoading(false)})()},[router]);
async function toggle(id:string){if(!supabase||busy)return;const {data:{session}}=await supabase.auth.getSession();if(!session)return;setBusy(id);const isFollowing=followingIds.has(id);const result=isFollowing?await supabase.from("follows").delete().eq("follower_id",session.user.id).eq("following_id",id):await supabase.from("follows").insert({follower_id:session.user.id,following_id:id});if(result.error)setToast(result.error.message);else setFollowingIds(prev=>{const n=new Set(prev);isFollowing?n.delete(id):n.add(id);return n});setBusy(null);setTimeout(()=>setToast(""),1800)}
if(loading)return <main className="social-page"><div className="social-loading">加载中…</div></main>;
return <main className="social-page"><header className="social-header"><button onClick={()=>router.back()}><ArrowLeft size={21}/></button><strong>粉丝</strong><span>{people.length}</span></header>{people.length?<section className="people-list">{people.map(p=><article className="person-row" key={p.id} onClick={()=>router.push(`/user/${encodeURIComponent(p.username)}`)}><div className="person-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:(p.display_name||p.nickname||p.username||"星").slice(0,1)}</div><div className="person-main"><b>{p.display_name||p.nickname||p.username}</b><span>@{p.username}</span>{p.bio&&<small>{p.bio}</small>}</div><button className={followingIds.has(p.id)?"person-follow following":"person-follow"} disabled={busy===p.id} onClick={e=>{e.stopPropagation();toggle(p.id)}}>{followingIds.has(p.id)?<><UserCheck size={15}/>已关注</>:<><UserPlus size={15}/>关注</>}</button></article>)}</section>:<section className="social-empty"><Users size={38}/><b>还没有粉丝</b><span>发布更多作品，让更多人发现你</span></section>}{toast&&<div className="toast">{toast}</div>}</main>}