"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, BarChart3, Eye, Heart, MessageCircle, Users, Video } from "lucide-react";
import { supabase } from "../../lib/supabase";

type Stats = { works:number; followers:number; following:number; likes:number; comments:number; views:number; views_7d:number };
type Work = { id:string; title:string|null; like_count:number|null; comment_count:number|null; created_at:string };
const fmt=(n:number)=>n>=1000000?`${(n/1000000).toFixed(1)}M`:n>=10000?`${(n/10000).toFixed(1)}万`:n>=1000?`${(n/1000).toFixed(1)}K`:String(n);

export default function CreatorDashboard(){
 const [stats,setStats]=useState<Stats|null>(null); const [works,setWorks]=useState<Work[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{if(!supabase){setError("Supabase 未配置");setLoading(false);return}const{data:{session}}=await supabase.auth.getSession();if(!session){location.href="/auth";return}const[{data:s,error:sErr},{data:w,error:wErr}]=await Promise.all([supabase.rpc("get_creator_stats"),supabase.from("videos").select("id,title,like_count,comment_count,created_at").eq("user_id",session.user.id).eq("status","published").order("created_at",{ascending:false}).limit(20)]);if(sErr||wErr){setError((sErr||wErr)?.message||"加载失败");setLoading(false);return}setStats((s?.[0] as Stats)||null);setWorks((w||[]) as Work[]);setLoading(false)})()},[]);
 if(loading)return <main className="creatorDash"><div className="dashLoading">正在加载创作者数据…</div></main>;
 return <main className="creatorDash"><style jsx global>{`.creatorDash{min-height:100dvh;background:#070707;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;padding-bottom:40px}.creatorHead{max-width:980px;margin:auto;padding:22px 20px;display:flex;align-items:center;gap:14px;border-bottom:1px solid #222}.creatorHead a{color:#aaa;display:grid;place-items:center}.creatorHead h1{font-size:21px;margin:0}.creatorBody{max-width:980px;margin:auto;padding:22px 20px}.dashLoading,.dashError{text-align:center;padding:90px 20px;color:#888}.statsGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{background:#111;border:1px solid #222;border-radius:16px;padding:18px}.statIcon{color:#aaa;margin-bottom:12px}.stat b{display:block;font-size:25px}.stat span{display:block;color:#888;font-size:12px;margin-top:5px}.sectionTitle{display:flex;align-items:center;gap:8px;margin:30px 0 12px;font-size:16px}.work{display:flex;justify-content:space-between;align-items:center;padding:15px 0;border-bottom:1px solid #1d1d1d}.workTitle{font-weight:700;max-width:55%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.workMeta{display:flex;gap:14px;color:#888;font-size:12px}.tip{margin-top:22px;color:#777;font-size:12px;line-height:1.7}@media(max-width:650px){.statsGrid{grid-template-columns:repeat(2,1fr)}.stat b{font-size:22px}}`}</style><header className="creatorHead"><Link href="/"><ArrowLeft size={21}/></Link><h1>创作者中心</h1></header><section className="creatorBody">{error?<div className="dashError">{error}</div>:stats&&<><div className="statsGrid"><div className="stat"><Eye className="statIcon" size={20}/><b>{fmt(stats.views)}</b><span>累计播放</span></div><div className="stat"><BarChart3 className="statIcon" size={20}/><b>{fmt(stats.views_7d)}</b><span>近7天播放</span></div><div className="stat"><Users className="statIcon" size={20}/><b>{fmt(stats.followers)}</b><span>粉丝</span></div><div className="stat"><Heart className="statIcon" size={20}/><b>{fmt(stats.likes)}</b><span>获赞</span></div></div><div className="statsGrid" style={{marginTop:12}}><div className="stat"><Video className="statIcon" size={20}/><b>{fmt(stats.works)}</b><span>作品</span></div><div className="stat"><MessageCircle className="statIcon" size={20}/><b>{fmt(stats.comments)}</b><span>评论</span></div><div className="stat"><Users className="statIcon" size={20}/><b>{fmt(stats.following)}</b><span>关注</span></div></div><h2 className="sectionTitle">最近作品</h2>{works.map(w=><Link className="work" href={`/video/${w.id}`} key={w.id}><span className="workTitle">{w.title||"分享一个瞬间"}</span><span className="workMeta"><span>♥ {fmt(w.like_count||0)}</span><span>评论 {fmt(w.comment_count||0)}</span></span></Link>)}<p className="tip">播放量统计来自视频曝光事件；点赞、评论来自作品实时数据。这个页面后续可以继续接入 7/30 天趋势图、涨粉来源和单条作品分析。</p></>}</section></main>;
}
