"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, Search, MessageCircle, Plus } from "lucide-react";
import { supabase } from "../../lib/supabase";

type Chat={id:string;displayName:string;avatar:string;lastMessage:string;time:string;unread:number};
export default function MessagesPage(){
 const [chats,setChats]=useState<Chat[]>([]);const [loading,setLoading]=useState(true);const [query,setQuery]=useState("");const [userId,setUserId]=useState<string|null>(null);
 useEffect(()=>{(async()=>{if(!supabase){setLoading(false);return}const {data:{session}}=await supabase.auth.getSession();if(!session){location.href="/auth";return}setUserId(session.user.id);const {data:members}=await supabase.from("conversation_members").select("conversation_id,user_id,last_read_at").eq("user_id",session.user.id);if(!members?.length){setLoading(false);return}const ids=members.map(x=>x.conversation_id);const {data:others}=await supabase.from("conversation_members").select("conversation_id,user_id").in("conversation_id",ids).neq("user_id",session.user.id);const otherIds=[...new Set((others||[]).map(x=>x.user_id))];const {data:profiles}=otherIds.length?await supabase.from("profiles").select("id,username,display_name,avatar_url").in("id",otherIds):{data:[] as any[]};const {data:msgs}=await supabase.from("messages").select("conversation_id,content,created_at,sender_id").in("conversation_id",ids).order("created_at",{ascending:false});const rows=(members||[]).map(m=>{const other=others?.find(x=>x.conversation_id===m.conversation_id);const p=profiles?.find(x=>x.id===other?.user_id);const last=msgs?.find(x=>x.conversation_id===m.conversation_id);const unread=msgs?.filter(x=>x.conversation_id===m.conversation_id&&x.sender_id!==session.user.id&&new Date(x.created_at)>new Date(m.last_read_at)).length||0;return{id:m.conversation_id,displayName:p?.display_name||p?.username||"星流用户",avatar:(p?.display_name||p?.username||"星").slice(0,1),lastMessage:last?.content||"开始聊天吧",time:last?formatTime(last.created_at):"",unread}});setChats(rows);setLoading(false)})();},[]);
 const filtered=chats.filter(x=>(x.displayName+x.lastMessage).toLowerCase().includes(query.toLowerCase()));
 return <main className="socialPage"><header className="socialHeader"><button onClick={()=>history.back()}><ArrowLeft/></button><h1>消息</h1><button onClick={()=>location.href="/following"}><Plus/></button></header><div className="messageSearch"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索私信"/></div>{loading?<div className="emptyState">正在加载消息…</div>:filtered.length?<div className="chatList">{filtered.map(c=><button className="chatRow" key={c.id} onClick={()=>location.href=`/messages/${c.id}`}><div className="socialAvatar">{c.avatar}</div><div className="chatMain"><div className="chatTitle"><b>{c.displayName}</b><small>{c.time}</small></div><div className="chatPreview">{c.lastMessage}</div></div>{c.unread>0&&<span className="unread">{c.unread>99?"99+":c.unread}</span>}</button>)}</div>:<div className="emptyState"><MessageCircle size={48}/><b>还没有私信</b><span>去关注页找一个朋友开始聊天</span><button className="primaryBtn" onClick={()=>location.href="/following"}>找人聊天</button></div>}<Bottom active="message" userId={userId}/></main>
}
function formatTime(s:string){const d=new Date(s);const now=new Date();if(d.toDateString()===now.toDateString())return d.toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"});return `${d.getMonth()+1}/${d.getDate()}`}
function Bottom({active,userId}:{active:string;userId:string|null}){return <nav className="socialNav"><button className={active==="home"?"on":""} onClick={()=>location.href="/"}>首页</button><button className={active==="follow"?"on":""} onClick={()=>location.href="/following"}>关注</button><button className={active==="message"?"on":""} onClick={()=>location.href="/messages"}>消息</button><button className={active==="profile"?"on":""} onClick={()=>location.href=userId?"/profile":"/auth"}>我</button></nav>}
