"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, MessageCircle, UserPlus, UserCheck } from "lucide-react";
import { supabase } from "../../lib/supabase";

type Person={id:string;username:string;displayName:string;avatar:string;following:boolean};
export default function FollowingPage(){
 const [tab,setTab]=useState<"following"|"followers">("following");const [people,setPeople]=useState<Person[]>([]);const [me,setMe]=useState<string|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{load()},[tab]);
 async function load(){if(!supabase)return;const {data:{session}}=await supabase.auth.getSession();if(!session){location.href="/auth";return}setMe(session.user.id);const field=tab==="following"?"follower_id":"following_id";const other=tab==="following"?"following_id":"follower_id";const {data:rows}=await supabase.from("follows").select(`follower_id,following_id`).eq(field,session.user.id);const ids=(rows||[]).map((x:any)=>x[other]).filter(Boolean);if(!ids.length){setPeople([]);setLoading(false);return}const {data:profiles}=await supabase.from("profiles").select("id,username,display_name,avatar_url").in("id",ids);let followingIds=new Set<string>();const {data:mine}=await supabase.from("follows").select("following_id").eq("follower_id",session.user.id);followingIds=new Set((mine||[]).map((x:any)=>x.following_id));setPeople((profiles||[]).map((p:any)=>({id:p.id,username:p.username||"user",displayName:p.display_name||p.username||"星流用户",avatar:(p.display_name||p.username||"星").slice(0,1),following:followingIds.has(p.id)})));setLoading(false)}
 async function toggle(p:Person){if(!supabase||!me)return;if(p.following){await supabase.from("follows").delete().eq("follower_id",me).eq("following_id",p.id)}else{await supabase.from("follows").insert({follower_id:me,following_id:p.id})}setPeople(x=>x.map(a=>a.id===p.id?{...a,following:!a.following}:a))}
 async function message(p:Person){if(!supabase||!me)return;const {data,error}=await supabase.rpc("ensure_conversation",{p_user_id:p.id});if(error){alert(error.message);return}location.href=`/messages/${data}`}
 return <main className="socialPage"><header className="socialHeader"><button onClick={()=>history.back()}><ArrowLeft/></button><h1>关注</h1><span/></header><div className="switchTabs"><button className={tab==="following"?"on":""} onClick={()=>setTab("following")}>关注</button><button className={tab==="followers"?"on":""} onClick={()=>setTab("followers")}>粉丝</button></div>{loading?<div className="emptyState">正在加载…</div>:people.length?<div className="peopleList">{people.map(p=><div className="personRow" key={p.id}><div className="socialAvatar">{p.avatar}</div><div className="personInfo"><b>{p.displayName}</b><small>@{p.username}</small></div><button className={p.following?"personBtn checked":"personBtn"} onClick={()=>toggle(p)}>{p.following?<><UserCheck size={17}/>已关注</>:<><UserPlus size={17}/>关注</>}</button>{tab==="following"&&<button className="dmBtn" onClick={()=>message(p)}><MessageCircle size={19}/></button>}</div>)}</div>:<div className="emptyState"><UserPlus size={48}/><b>{tab==="following"?"还没有关注任何人":"还没有粉丝"}</b><span>去首页发现更多有趣的人</span><button className="primaryBtn" onClick={()=>location.href="/"}>去首页</button></div>}</main>
}
